# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_type', models.CharField(max_length=20)),
                ('source_file', models.CharField(max_length=200)),
                ('output_file', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date created')),
            ],
        ),
    ]
