# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statsForOrg', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statfile',
            old_name='pub_date',
            new_name='creation_date',
        ),
        migrations.AddField(
            model_name='statfile',
            name='year',
            field=models.IntegerField(default=9999),
            preserve_default=False,
        ),
    ]
